Web/AcCms.Web/Areas/admin/Controllers/AuthenticationController.cs
using AcCms.Models.Authentication;
using AcCms.Models.Enumeration;
using AcCms.Services.Admin.Mvc;
using AcCms.Services.Common.Authentication;
using Core.CommonModels;
using Core.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcCms.Web.Areas.admin.Controllers
{
    public class AuthenticationController : AdminMvcControllerBaseWithIdentity
    {
      private readonly AuthenticationService _authenticationService;
        public AuthenticationController(WebIdentity identity, AuthenticationService authenticationService) : base(identity)
        {
            _authenticationService = authenticationService;
        }

        public ActionResult Login(string returnUrl)
        {
            if (Identity.IsAuthenticated)
            {
                if (Identity.AllowAccess(Enums.Privilege.AdminAccess))
                {
                    return RedirectToAction("Index", "Dashboard");
                }
            }

            ViewBag.ReturnURL = returnUrl;
            ViewBag.CaptchaImage = ResetCaptcha();
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model, string capchatoken)
        {
            if (Identity.IsAuthenticated)
            {
                if (Identity.AllowAccess(Enums.Privilege.AdminAccess))
                {
                    return RedirectToAction("Index", "Dashboard");
                }
            }

            if (!String.IsNullOrEmpty(capchatoken) && Session["Captcha"] != null && String.Equals(capchatoken, Session["Captcha"].ToString()))
            {
                List<KeyValue> validationErrors;
                if (AcValidationProvider.Validate(ModelState, p => p, out validationErrors))
                {
                    Guid token;
                    var result = _authenticationService.Login(model, out token);
                    if (result == Enums.LoginResult.Failed)
                    {
                        Message.Error = "Wrong email or password.";
                    }
                    else if (result == Enums.LoginResult.RequireEmailValidation)
                    {
                        Message.Error = "Please verify your email address.";
                    }
                    else if (result == Enums.LoginResult.NotActive)
                    {
                        Message.Error = "Your user is inactive.";
                    }
                    else
                    {
                        Identity.SignIn(token);

                        return RedirectToAction("Index", "Dashboard");
                    }
                }
                else
                {
                    Message.Error = "Please check errors.";
                }
            }
            else {
                Message.Error = "Please check captcha.";
            }

            ViewBag.CaptchaImage = ResetCaptcha();
            return View(model);
        }

        public ActionResult LogOut()
        {
            _authenticationService.Logout(Identity.Id, Identity.Token);
            Identity.SignOut();

            return RedirectToAction("Index", "Dashboard");
        }

        [AllowAnonymous]
        public ActionResult RerenderCaptcha()
        {
            return Json(new { result = ResetCaptcha() }, JsonRequestBehavior.AllowGet);
        }
        public string ResetCaptcha()
        {
            var rand = new Random((int)DateTime.Now.Ticks);
            string captcha = rand.Next(100000, 999999).ToString();
            Session["Captcha"] = captcha;

            return _.Web.CaptchaImage(captcha);
        }
    }
}

Web/AcCms.Web/Areas/admin/Views/Authentication/Login.cshtml
@model LoginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="tr">
<head>
    @Html.Partial("~/Areas/admin/Views/Layout/_head.cshtml")
</head>
@Html.Partial("_AdminMessage")
<body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default" cz-shortcut-listen="true" style="background-color:transparent">
    <div class="m-grid m-grid--hor m-grid--root m-page">
        <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-2" id="m_login" style="background-image: url(./assets/app/media/img//bg/bg-3.jpg);">
            <div class="m-grid__item m-grid__item--fluid	m-login__wrapper">
                <div class="m-login__container">
                    <div class="m-login__logo">
                        <a href="#">
                            <img src="~/AdminTheme/logo.png" style="width: 25%" />
                        </a>
                    </div>
                    <div class="m-login__signin">
                        <div class="m-login__head">
                            <h3 class="m-login__title">Giriş Yap</h3>
                        </div>
                        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "m-login__form m-form" }))
                        {
                            <div class="form-group m-form__group">
                                @Html.TextBoxFor(m => m.Email, new { placeholder = "Email", @class = "form-control m-input" })
                                @Html.ValidationMessageFor(m => m.Email, null, new { @class = "m-form__help m--font-danger" })
                            </div>
                            <div class="form-group m-form__group">
                                @Html.PasswordFor(m => m.Password, new { placeholder = "Şifre", @class = "form-control m-input", autocomplete = "off" })
                                @Html.ValidationMessageFor(m => m.Password, null, new { @class = "m-form__help m--font-danger" })
                            </div>
                            <div class="form-group m-form__group">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="row">
                                                <div class="captcha-container" style="background: #82dfb4; padding: 10px; border-radius: 30px;">
                                                    <img src="data:image/png;base64,@ViewBag.CaptchaImage" class="captcha-image" style="width: 90px;" />
                                                    <img class="captcha-button" src="~/AdminTheme/captcha-button.png" style="width: 20px; margin-left: 10px; cursor: pointer;" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="row">
                                                <input type="text" name="capchatoken" class="form-control m-input" placeholder="Captcha" style="margin-top:0;" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-login__form-action">
                                <button id="m_login_signin_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary">GİRİŞ YAP</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("~/Areas/admin/Views/Layout/_scripts.cshtml")
    <script>
        $(document).ready(function () {
            $('.captcha-button').click(function () {
                GetCaptcha();
            });
        });

        var captchaProccess = 0;
        function GetCaptcha() {
            if (captchaProccess == 0) {
                captchaProccess = 1;
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("RerenderCaptcha","Authentication")",
                    success: function (data) {
                        $('.captcha-image').attr("src", "data:image/png;base64," + data.result);
                        captchaProccess = 0;
                    },
                    error: function (data) {
                        alert('Bir hata oluştu!');
                        captchaProccess = 0;
                    }
                });
            }
        }
    </script>
</body>
</html>